apiVersion: discovery.k8s.io/v1 
kind: EndpointSlice
metadata:
  name: manual change 
  labels:
    kubernetes.io/service-name: example
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "pods-ip"
