# pod-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-intern
  namespace: test-team
rules:
- apiGroups: [""]     # core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

