# pod-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: test-team
subjects:
- kind: user 
  name: pod-intern 
  namespace: test-team 
roleRef:
  kind: Role
  name: pod-intern 
  apiGroup: rbac.authorization.k8s.io

